version: 2
updates:
  - package-ecosystem: gomod
    directory: /BlackRadar
    schedule:
      interval: monthly
    groups:
      all-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      all-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /BlackRadar/ui
    schedule:
      interval: monthly
    groups:
      all-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      all-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /BlackRadar
    schedule:
      interval: monthly
    groups:
      all-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      all-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      all-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      all-security:
        applies-to: security-updates
        patterns:
          - "*"
